services:
  demo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensearch-demo-server
    ports:
      - "5000:8080" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: opensearch-demo-network
