services:
  demo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opensearch-demo-server
    ports:
      - "5000:8080"  # HTTP
      - "5001:8081"  # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./data:/app/data  # Mount data directory for sync statistics
      - ~/.aspnet/https:/https:ro  # Mount HTTPS certificates (optional)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  default:
    name: opensearch-demo-network
